# Generated by Django 3.2.6 on 2021-08-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='css_file',
            field=models.TextField(null=True),
        ),
    ]
